### ISSUE TITLE
v2 -> v3 roadmap

### ISSUE THREAD

**Issue by jacoobes** [sern-handler/handler#201]
# sern v2

Join our [discord](https://sern.dev/discord) for direct communications. I'm most active there!

## [Handler](https://github.com/sern-handler/handler) 
- [x] https://sern.dev/blog
  - finished v2 (changes are in this blog)
- [x] sern 2.5 blog  
- [x] update guide to reflect 2.5
- [x] add testing
     - [x] test dep injection
     - [x] test EVERYTHING
- [ ] pattern matching text commands #290 
- [ ] lazy modules
# Post sern v2 (looking at the future)
## Experimental
- [ ] @sern/rx package (version 1 stable)
- [ ] decorators ( wait until typescript version 5)
- [x] update plugin usage #193  (breaking changes)
- [x] expand to different targets (eris, discord.js, etc) (deferred)
~~helper functions for different command types~~
~~function command modules?~~
## Planned
- [x] update internals and modularize #193  (very convoluted and hard to contribute to) 
- [ ] website revamp with automated documentation generated
- [x] update class based modules
- [ ] Example Bot
- [ ] analyze performance and decrease memory consumption
- [x] cli update and refactoring sern-handler/cli#105
- [x] sern templates updates
- [ ] plugin page in website 
- [x] plugin lock file
- [x] audit ts-pattern and ts-results-es #256 
    - can we remove? 
    - are they necessary?
    - any alternatives?
- [x] abstract and protect internals so sern is more resistant to breaking changes #294
